### ISSUE TITLE
ouhtml-orchestra-login-portal custom security context capabilities

### ISSUE THREAD

**Issue by fos016** [OpenUnison/helm-charts#126]
It's due to eks version and compatiblity. The defaults are not supporte. Could it configurable throught values file?

**Comment by mlbiam** [comment]
we could do that, but what is failing?  The default security profile is really restrictive already.

**Comment by fos016** [comment]
Yes, but maybe it is not full supported due eks version

**Comment by fos016** [comment]
Example: 

W1218 09:23:43.371852   15128 warnings.go:70] would violate PodSecurity "restricted:latest": unrestricted capabilities (container "test-values" must set securityContext.capabilities.drop=["ALL"])
W1218 09:23:48.611675   15128 warnings.go:70] would violate PodSecurity "restricted:latest": unrestricted capabilities (container "kube-oidc-proxy-orchestra" must set securityContext.capabilities.drop=["ALL"])
W1218 09:23:48.618080   15128 warnings.go:70] would violate PodSecurity "restricted:latest": unrestricted capabilities (container "openunison-orchestra" must set securityContext.capabilities.drop=["ALL"])
W1218 09:23:48.651247   15128 warnings.go:70] would violate PodSecurity "restricted:latest": unrestricted capabilities (container "check-certs-orchestra" must set securityContext.capabilities.drop=["ALL"])

**Comment by mlbiam** [comment]
interesting.  that's strange since we set those at the `Pod` level.  Easy enough to do there too

**Comment by mlbiam** [comment]
updated the charts.  pull down the latest and try redeploying with ouctl.  I tested with PSA enabled on the openunison namespace (`pod-security.kubernetes.io/enforce: restricted`).  Here's the chart versions you should have deployed:

```
helm list -n openunison
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
openunison              openunison      8               2023-12-18 10:17:37.99608 -0500 EST     deployed        openunison-operator-3.0.8       1.0.38     
orchestra               openunison      5               2023-12-18 10:17:42.364379 -0500 EST    deployed        orchestra-2.10.39               1.0.38     
orchestra-login-portal  openunison      5               2023-12-18 10:18:59.237418 -0500 EST    deployed        orchestra-login-portal-2.3.40   1.0.38     
```

**Comment by fos016** [comment]
It worked ;) thanks for your quick response
