### ISSUE TITLE
batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob

### ISSUE THREAD

**Issue by grig777** [OpenUnison/helm-charts#59]
It will be nice to have an updated batch job API version to be able to install openunison auth login portal in v1.25+ version Kubernetes via helm chart and `ouctl` command

**Comment by mlbiam** [comment]
run `helm repo update` and redeploy.  Shouldn't be any issues with `CronJob` now
